In [ ]:
import numpy as np
import pandas as pd
from sklearn import tree

In [ ]:
Dataset = pd.read_csv('customer-churn-data.csv',delimiter=',',header=0)

In [ ]:
Dataset.head()

Gender  Age PaymentMethod  Churn  LastTransaction
0    male   64   credit card  loyal               98
1    male   35        cheque  churn              118
2  female   25   credit card  loyal              107
3  female   39   credit card    NaN              177
4    male   39   credit card  loyal               90

In [ ]:
Dataset.isna().sum()

Gender              0
Age                 0
PaymentMethod       0
Churn              47
LastTransaction     0
dtype: int64

In [ ]:
Dataset_Churn = Dataset
modus = Dataset_Churn['Churn'].mode()[0]
Dataset_Churn['Churn'] = Dataset_Churn['Churn'].fillna(modus)
Dataset_Churn['Churn'].isna().sum()

0

In [ ]:
Dataset.head()

Gender  Age PaymentMethod  Churn  LastTransaction
0    male   64   credit card  loyal               98
1    male   35        cheque  churn              118
2  female   25   credit card  loyal              107
3  female   39   credit card  loyal              177
4    male   39   credit card  loyal               90

In [ ]:
Dataset["Churn"] = pd.factorize(Dataset.Churn)[0]
Dataset["Gender"] = pd.factorize(Dataset.Gender)[0]
Dataset["PaymentMethod"] = pd.factorize(Dataset.PaymentMethod)[0]

In [ ]:
Dataset.head()

Gender  Age  PaymentMethod  Churn  LastTransaction
0       0   64              0      0               98
1       0   35              1      1              118
2       1   25              0      0              107
3       1   39              0      0              177
4       0   39              0      0               90

In [ ]:
print(Dataset)

     Gender  Age  PaymentMethod  Churn  LastTransaction
0         0   64              0      0               98
1         0   35              1      1              118
2         1   25              0      0              107
3         1   39              0      0              177
4         0   39              0      0               90
..      ...  ...            ...    ...              ...
495       0   46              0      0               92
496       1   69              2      0              116
497       1   55              1      1              146
498       1   27              0      0               37
499       0   79              2      1               96

[500 rows x 5 columns]


In [ ]:
Dataset = Dataset.to_numpy()

In [ ]:
print(Dataset)

[[  0  64   0   0  98]
 [  0  35   1   1 118]
 [  1  25   0   0 107]
 ...
 [  1  55   1   1 146]
 [  1  27   0   0  37]
 [  0  79   2   1  96]]


In [ ]:
dataTraining = np.concatenate((Dataset[0:200, :], Dataset[250:450, :]),
                              axis=0)
dataTesting = np.concatenate((Dataset[200:250, :], Dataset[450:500, :]),
                             axis=0)

In [ ]:
print(dataTraining)
len(dataTraining)

[[  0  64   0   0  98]
 [  0  35   1   1 118]
 [  1  25   0   0 107]
 ...
 [  0  61   0   0  55]
 [  0  49   0   0  67]
 [  0  54   0   0  21]]


400

In [ ]:
print(dataTesting)
len(dataTesting)

[[  0  75   0   0 172]
 [  0  40   0   0  74]
 [  0  30   0   0  77]
 [  0  42   2   0 149]
 [  1  43   2   0  72]
 [  0  61   2   1 140]
 [  0  56   0   0  46]
 [  1  51   0   1 179]
 [  0  37   0   0 109]
 [  0  17   1   0 138]
 [  1  30   0   0 111]
 [  1  35   2   1 120]
 [  0  25   2   1 152]
 [  0  26   0   0 107]
 [  1  33   0   1 191]
 [  1  43   0   1 184]
 [  0  21   2   0 103]
 [  0  29   0   0  75]
 [  0  34   2   0 118]
 [  1  33   0   1 162]
 [  0  17   0   0 103]
 [  1  79   0   1 141]
 [  0  79   0   0 160]
 [  0  52   0   0 115]
 [  1  62   1   1 136]
 [  1  30   0   0 137]
 [  1  35   0   1 141]
 [  0  31   0   0  55]
 [  1  47   2   1 163]
 [  0  35   0   0 107]
 [  0  61   0   0  94]
 [  0  62   0   0  82]
 [  1  55   0   0 155]
 [  0  48   1   0 143]
 [  0  89   2   0 132]
 [  1  33   0   1 172]
 [  1  50   0   0 194]
 [  0  63   1   1 196]
 [  1  64   0   1  61]
 [  0  74   0   0 190]
 [  0  33   0   0 111]
 [  0  55   1   0 128]
 [  0  81   0   0 149]
 [  1  81  

100

In [109]:
inputTraining = dataTraining[:,0:3]
inputTesting = dataTesting[:,0:3]
labelTraining = dataTraining[:,3]
labelTesting = dataTesting[:,3]

In [110]:
model = tree.DecisionTreeClassifier()

In [111]:
model = model.fit(inputTraining, labelTraining)

In [112]:
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi :", hasilPrediksi)

Label Sebenarnya :  [0 0 0 0 0 1 0 1 0 0 0 1 1 0 1 1 0 0 0 1 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0
 1 1 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 0 1 1 1 1 0 0 1 0 1 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 1 1 0 0 1 0 1]
Hasil Prediksi : [0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1
 0 1 0 0 0 1 0 0 1 1 1 1 0 0 0 0 1 1 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 1 0 0 1 0 0 0]


In [113]:
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar :", prediksiBenar,"data")
print("Prediksi Salah :", prediksiSalah,"data")
print("Akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah)*100, "%")

Prediksi Benar : 69 data
Prediksi Salah : 31 data
Akurasi : 69.0 %
